### ISSUE TITLE
Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by lucas-bogos** [yuvraj108c/instagram-publisher#4]
The lib works normally on localhost, but in production it occurs this error.

**Comment by lucas-bogos** [comment]
`{"error":{"name":"StatusCodeError","statusCode":429}}`

**Comment by lucas-bogos** [comment]
Do you have any limit on requests?

**Comment by yuvraj108c** [comment]
Hii, statuscode 429 indicates that you have made too many requests and instagram may have blocked your ip temporarily.
Try changing your ip address or try again later. The last resort is to delete the cached cookies and re-authenticate the client.
