### ISSUE TITLE
Question: Thumbnail really needed?

### ISSUE THREAD

**Issue by haupt-pascal** [yuvraj108c/instagram-publisher#5]
My question is: Is a thumbnail really needed? 

If I want to upload my reel manually, instagram doesn’t want a thumbnail from me. Why do I have to give one as input in this script? 

How does the publisher handle the upload if I give a empty path as input?

**Comment by yuvraj108c** [comment]
Yes, a thumbnail is required. This NPM package is based on the instagram web client, where thumbnails are necessary while uploading reels/videos. It will not work if empty paths are provided. 

This NPM package can be useful for extracting a frame from a video: https://www.npmjs.com/package/ffmpeg-extract-frames
