### ISSUE TITLE
Cached credentials

### ISSUE THREAD

**Issue by haupt-pascal** [yuvraj108c/instagram-publisher#6]
Hey,

sorry for the new ticket/question again, but I have a little problem. 

I use this package to upload videos to different channels, but the first login is cached and the other ones will be uploaded to the same instagram account like the first one. Is there any way to disable / clear the cache before the upload?

**Comment by yuvraj108c** [comment]
Hi, I have not yet implemented support for different accounts, but it can be easily done on your side. Generate/delete the `cookies.json` file programmatically using a script, based on the account you're using
